### ISSUE TITLE
Is will be excluded chapter about OData from second edition? 

### ISSUE THREAD

**Issue by P9avel** [markjprice/apps-services-net8#1]
In first edition was '10 Exposing Data via the Web Using OData' chapter. But i cannot to find this chapter in second edition. Do yo removed this chapter? Why?

**Comment by markjprice** [comment]
To make space for new content like *Chapter 9, Caching, Queuing, and Resilient Background Services*, some content from the first edition is now online-only: https://github.com/markjprice/apps-services-net8/blob/main/docs/README.md
