### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DocVD** [markjprice/apps-services-net8#13]
Page 33: Second bullet in Exercise 1.2
     Benchmarking Performance and Testing: In this section, you will learn how to use types in 
     the System.Diagnostics namespace and the Benchmark.NET library to monitor your code 
     to measure performance and efficiency (**https://github.com/markjprice/apps-services
     net8/blob/main/docs/ch01-benchmarking.md**).

Easy issue fix: The actual URL has a hyphen between the words "services" and "net8", so the link should be:
https://github.com/markjprice/apps-**services-net8**/blob/main/docs/ch01-benchmarking.md

**Comment by markjprice** [comment]
The link is correct in the PDF:
![image](https://github.com/markjprice/apps-services-net8/assets/14040265/0115d6f9-c72b-457c-aae3-cc202f3be747)
Where is the hyphen missing for you?
