### ISSUE TITLE
Example switches from Model to ViewData change.

### ISSUE THREAD

**Issue by Pip1987** [markjprice/apps-services-net8#14]
On Page 1027-1028 (Kindle is hard to pinpoint) the example shows:
```
model.ShipperSummary = "Shipper from gRPC service:" +
    $"ID:{shipperReply.ShipperId}, Name:ShipperReply.CompanyName
    ....
```
however on page 1040 instead of assigning the information to ``model.ShipperSummary`` it assigns the data to ``ViewData["shipper"]``.

**Comment by markjprice** [comment]
Thanks Phil. I have added an item for this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-595---getting-request-and-response-metadata
