### ISSUE TITLE
Missing Form from Products Chapter 13

### ISSUE THREAD

**Issue by Pip1987** [markjprice/apps-services-net8#15]
The form to search for product in chapter 13 page 1061 (Kindle) is missing from the in text version. The repository version has it. 
```
<form asp-action="Products" method="post">
    <input name="minimumPrice" placeholder="Enter a minimum unit price" />
    <input type="submit" value="Filter Products" />
</form>
```

**Comment by markjprice** [comment]
Thanks, Phil. I have added an item for this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-607---adding-product-and-employee-grpc-clients
