### ISSUE TITLE
Incorrect code: Chapter 1A - What's New in Modern C# and .NET -> Using declarations

### ISSUE THREAD

**Issue by gelverpl** [markjprice/apps-services-net8#16]
It looks like there is a mistake in the second block of the code in [this](https://github.com/markjprice/apps-services-net8/blob/main/docs/ch01-whats-new.md#using-declarations) online section:
![image](https://github.com/markjprice/apps-services-net8/assets/33697481/2f01bbc9-bf41-4a4d-ab1c-f42f645a5a4d)

You probably forgot to remove the brackets and it should look like this:
```cs
using FileStream file = File.OpenWrite(Path.Combine(path, "file.txt"));
...
// automatically calls Dispose at the end of current scope if the file is not null
```

**Comment by markjprice** [comment]
Yes, thank you. Fixed now.
