### ISSUE TITLE
Program.cs for Minimal Web Services in Chapter 15.

### ISSUE THREAD

**Issue by DocVD** [markjprice/apps-services-net8#19]
On page 695, in Step-7, Configuring HttpJsonOptions, the added first letter in "Options" should be lowercase instead of uppercase.

On page 696. in Step-8, app.MapGet("api/employees/{id:int}, the first letter should be uppercase instead of lowercase for "employee" in:
- if:      "if (employee" and 
- else:  "else { return Results.Json(employee"

**Comment by markjprice** [comment]
Thanks. I've added an errata for this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-695---getting-entities-into-a-component-by-building-a-web-service
