### ISSUE TITLE
Comments in json docs cause issues for JWT creation.

### ISSUE THREAD

**Issue by Pip1987** [markjprice/apps-services-net8#6]
Creating a JWT token as shown on page 652; `dotnet user-jwts create` results in `'/' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 5 | BytePositionInLine: 6.` if you have any comments in `appsettings.json`, `appsettings.Development.json`, or `launchSettings.json`.

**Comment by markjprice** [comment]
Thanks! I have added an errata item about this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-328---configuring-http-logging-for-the-web-service-and-page-363---authenticating-service-clients-using-jwt-bearer-authentication
