### ISSUE TITLE
Chapter 8 Online Section http linebreaks not working

### ISSUE THREAD

**Issue by Pip1987** [markjprice/apps-services-net8#7]
*** This is a Visual Studio issue see comment below.***
I'm working through chapter 8's online section for odata when I try the request
```
###
GET {{base_address}}categories/
  ?$select=CategoryId,CategoryName
``` 
it returns
```
{
  "@odata.context": "https://localhost:5084/catalog/$metadata#Categories",
  "value": [
    {
      "CategoryId": 1,
      "CategoryName": "Beverages",
      "Description": "Soft drinks, coffees, teas, beers, and ales",
       .......
```
and I have an error stating ``'?$select=CategoryId,CategoryName' is not a valid http header. Expecting a valid http header or a blank line to separate the header section from the request body.	``
when I run the request as a single line ``GET {{base_address}}categories/?$select=CategoryId,CategoryName`` the output is correct.
```
{
  "@odata.context": "https://localhost:5084/catalog/$metadata#Categories(CategoryId,CategoryName)",
  "value": [
    {
      "CategoryId": 1,
      "CategoryName": "Beverages"
    },
    {
      "CategoryId": 2,
      "CategoryName": "Condiments"
    },
    ...
```
I've tried both with and without indent on the the ?$select line.

P.S.
And I know I've done a few issues, but honestly this book and the previous have been really helpful on learning new things and how to do other things better with c#. I've been really enjoying the books.

**Comment by markjprice** [comment]
Thanks! I have added an errata item for this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-366---exercise-84--exposing-data-via-the-web-using-odata-services

p.s. I'm happy to hear that you're enjoying the books. I really appreciate you taking the time to raise these issues that help everyone. Keep them coming! 

p.p.s. I'm busy writing the third book and have deadlines every Monday for new chapters so I don't have as much time as usual to investigate issues but quick ones like these I try to get to.
