### ISSUE TITLE
Missing .NET 8.0 option from Azure Function (Fixed but wanted to share the fix.)

### ISSUE THREAD

**Issue by Pip1987** [markjprice/apps-services-net8#9]
I had an issue where I had the Azure Tool set installed in VS2022, but when I went to create a function, I did not have the option to select .NET 8. In order to fix this. Go to Tools -> Options -> Project and Solutions -> Azure Functions. Click check for updates.

**Comment by markjprice** [comment]
Thanks! I have added an item for this:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/improvements.md#page-445---installing-azure-functions-core-tools
